/* eslint-disable @typescript-eslint/no-explicit-any */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactNode } from "react";
import { Toaster } from "react-hot-toast";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import LocaleSwitcher from "@/components/LocaleSwitcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: ReactNode;
  params: { locale: string };
};
const Layout = async ({ children, params: { locale } }: LayoutProps) => {
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  const dir = locale === "ar" ? "rtl" : "ltr";

  return (
    <html lang={locale} dir={dir}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <main className="flex items-center justify-center min-h-screen bg-gray-100">
            <LocaleSwitcher />
            <div className="bg-white p-8 rounded-lg shadow-md w-full max-w-md">
              {children}
              <Toaster />
            </div>
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export { metadata };
export default Layout;
